name: GitStats

# Controls when the action will run. 
on:
  # Triggers the workflow on a schedule
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '12 0 * * 1' #This runs on Mondays at 12:00PM UTC, 6:00am Boise time

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "Gather-Stats"
  Gather-Stats:
    # The type of runner VM that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # for posts's lastmod

      # Runs a set of commands using the runners shell
      - name: Set-up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
      - name: Run GitStats
        run: | 
          DATE=$(date +"%m.%d.%y")
          ORG="hydroframe"
          NEW_DIR=$DATE"-Update-n."${GITHUB_RUN_NUMBER}
          mkdir "$GITHUB_WORKSPACE/GitStats/$NEW_DIR"
          
          repos=(
              pfclm-flask-app
              Subsetting
              SandTank
              ParFlow_PerfTeam
              parflowio
              USRDATS
              parflow-performance-benchmark-flask-api
              PF_Model_Evaluation
              princeton-performance-benchmark-react-app
              adapt-performance-benchmark-react-app
              KeplerWF-flask-app
              ParflowPerformanceTesting
              pfclm-flask-interactive
              pfclm-javascript-app
              Post_Processing
              Workflows
              tools
              IanHydroframeWork
              Subsetting_Web
              Reservoir_Operations
              ParFlow_CombinedShortCourse
              ParFlow_Short_Course
              ParFlow_Advanced_ShortCourse
              Topography_processing
              Base_Images
              Forcing_Tools
              ParFlow_Docker
          )   
          
          for repo in "${repos[@]}"; do
            GITSTATS=$(curl -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.PAT }}" https://api.github.com/repos/$ORG/$repo/traffic/clones)
            echo $GITSTATS > "$GITHUB_WORKSPACE/GitStats/$NEW_DIR/$repo-clones.json"
            
            GITSTATS=$(curl -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.PAT }}" https://api.github.com/repos/$ORG/$repo/traffic/views)
            echo $GITSTATS > "$GITHUB_WORKSPACE/GitStats/$NEW_DIR/$repo-views.json"
          done
          
      - name: Push files to repo
        run: |
          git update-ref -d HEAD
          git add -A
          git commit -m "[Automation] GitStats update No.${GITHUB_RUN_NUMBER}"
          git push -f
        

